### ISSUE TITLE
thespaghettidetective_web_1 keeps restarting

### ISSUE THREAD

**Issue by Mavi222** [TheSpaghettiDetective/TheSpaghettiDetective#194]
Hey, I just finished installing the server, but in the docker, the thespaghettidetective_web_1 keeps restarting.
![image](https://user-images.githubusercontent.com/20151483/81402192-3bbeb380-9131-11ea-81ad-7635263176a3.png)
It goes on and off all the time, and after a while it's off, saying "restarting"
It happens even when my firewall is turned off.
I am running Windows 10 Pro 64bit.

This is the log from the docker:

> return self._save(name, content)
>   File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 242, in _save
>     os.makedirs(directory)
>   File "/usr/local/lib/python3.6/os.py", line 210, in makedirs
>     makedirs(head, mode, exist_ok)
>   File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 1] Operation not permitted: '/app/static_build'
> /usr/local/lib/python3.6/site-packages/daphne/server.py:13: UserWarning: Something has already installed a non-asyncio Twisted reactor. Attempting to uninstall it; you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on.
>   UserWarning,
> Traceback (most recent call last):
>   File "manage.py", line 15, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
>     collected = self.collect()
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
>     handler(path, prefixed_path, storage)
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 352, in copy_file
>     self.storage.save(prefixed_path, source_file)
>   File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 52, in save

I am sorry if this is something trivial, I am complete noob in this. What should I check to fix this issue?

Thanks a lot for answer, 

Mavi

**Comment by Mavi222** [comment]
I guess I resolved my issue by running the Docker as administrator.
