### ISSUE TITLE
Newest commits won't run (95c9f16)

### ISSUE THREAD

**Issue by derekslenk** [TheSpaghettiDetective/TheSpaghettiDetective#201]
Current master at commit 95c9f166b712cbfa2bf1100b878c30ddbd6595bd and previous in the merge (d91ee90) won't run. It will build fine but upon load,  only get a 500 server error.

In the logs:
```
django.request ERROR    Internal Server Error: /accounts/login/,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner,
    response = get_response(request),
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response,
    response = self.process_exception_by_middleware(e, request),
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response,
    response = response.render(),
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 106, in render,
    self.content = self.rendered_content,
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content,
    content = template.render(context, self._request),
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render,
    return self.template.render(context),
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 171, in render,
    return self._render(context),
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 163, in _render,
    return self.nodelist.render(context),
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 937, in render,
    bit = node.render_annotated(context),
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated,
    return self.render(context),
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render,
    return compiled_parent._render(context),
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 163, in _render,
    return self.nodelist.render(context),
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 937, in render,
    bit = node.render_annotated(context),
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated,
    return self.render(context),
  File "/usr/local/lib/python3.6/site-packages/django/template/library.py", line 192, in render,
    output = self.func(*resolved_args, **resolved_kwargs),
  File "/app/app/templatetags/vue.py", line 27, in bundle,
    url = static(f'{STATIC_BUNDLE_PREFIX}/{ext}/{bundle_name}.{ext}'),
  File "/usr/local/lib/python3.6/site-packages/django/templatetags/static.py", line 167, in static,
    return StaticNode.handle_simple(path),
  File "/usr/local/lib/python3.6/site-packages/django/templatetags/static.py", line 118, in handle_simple,
    return staticfiles_storage.url(path),
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 153, in url,
    return self._url(self.stored_name, name, force),
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url,
    hashed_name = hashed_name_func(*args),
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 420, in stored_name,
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name),
ValueError: Missing staticfiles manifest entry for 'frontend/js/main.js',
django.channels.server ERROR    HTTP GET /accounts/login/?next=/printers/ 500 [0.21, 192.168.12.100:59572],
django.request WARNING  Not Found: /favicon.ico,
```

Going back to bf3e4e0 and TSD works fine.

```
docker --version
Docker version 19.03.9, build 9d988398e7
```

```
docker-compose --version
docker-compose version 1.25.0, build 0a186604
```
```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 52
  Running: 52
  Paused: 0
  Stopped: 0
 Images: 188
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-9-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 23.54GiB
 Name: defiant.slenk.pw
 ID: JSRP:3N4B:6RJY:CJJX:WV44:CHOQ:HIKS:RR4L:PDVU:RQWF:BRW5:KHFQ
 Docker Root Dir: /docker/data
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by kennethjiang** [comment]
Thank you @derekslenk for reporting this bug! I reverted d91ee90 for now. I still know too little about Vue to mess around. ;)

Please pull and let me know if it's fixed now.

**Comment by derekslenk** [comment]
> 
> 
> Thank you @derekslenk for reporting this bug! I reverted [d91ee90](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/commit/d91ee90d4a6ec1881235a4544f6df2cba2d91ba8) for now. I still know too little about Vue to mess around. ;)
> 
> Please pull and let me know if it's fixed now.

Working again, thanks for the quick response!
