### ISSUE TITLE
web crashing when docker-compose version changed to 3.0

### ISSUE THREAD

**Issue by sebasptsch** [TheSpaghettiDetective/TheSpaghettiDetective#207]
So, as part of another project I've converted the exsisting docker-compose to version 3.0. I seem to have everything working aside from an error I get from the web container.
```
web_1     | /usr/local/lib/python3.6/site-packages/daphne/server.py:13: UserWarning: Something has already installed a non-asyncio Twisted reactor. Attempting to uninstall it; you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on.
web_1     |   UserWarning,
web_1     | Traceback (most recent call last):
web_1     |   File "manage.py", line 15, in <module>
web_1     |     execute_from_command_line(sys.argv)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
web_1     |     utility.execute()
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
web_1     |     django.setup()
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
web_1     |     apps.populate(settings.INSTALLED_APPS)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
web_1     |     app_config = AppConfig.create(entry)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
web_1     |     module = import_module(entry)
web_1     |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
web_1     |     return _bootstrap._gcd_import(name[level:], package, level)
web_1     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
web_1     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
web_1     |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
web_1     | ModuleNotFoundError: No module named 'webpack_loader'
```
Error seems similar to that of #194 but running compose as sudo doesn't seem to fix it.

**Comment by sebasptsch** [comment]
Issue was old containers with weird permissions.
