### ISSUE TITLE
Not found for url http://ipaddr/api/octo/pic/

### ISSUE THREAD

**Issue by nzzane** [TheSpaghettiDetective/TheSpaghettiDetective#255]
Hey,

OctoPi - Raspberry Pi 3b
Octopi 0.17.0
Octoprint 1.4.0

Plugin version;
Access Anywhere - The Spaghetti Detective; 1.3.2

Webcam stream is a bit laggy too, and the timelapse section won't load any image / video. (Have gone through the laggy stream troubleshooting steps)
I can see the printer in TSD, and control it, so just seems to be an issue with the webcam stream.

Diagnostic report says it failed to connect around 1000 times, unsure if this is related, but secret token says secret is valid, then goes to unknown error straight after
Unsure if this is something in my setup, unsure where to go from here

````
2020-07-21 07:50:48,824 - octoprint_thespaghettidetective_beta.utils - ERROR - Backing off 0.215390 seconds: 404 Client Error: Not Found for url: http://192.168.1.181:3334/api/octo/pic/
2020-07-21 07:50:48,854 - sentry.errors - ERROR - Sentry responded with an error: <urlopen error [Errno -2] Name or service not known> (url: https://sentry.getanywhere.io/api/3/store/)

Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 165, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/home/pi/oprint/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)

URLError: <urlopen error [Errno -2] Name or service not known>
2020-07-21 07:50:48,855 - sentry.errors.uncaught - ERROR - [u'HTTPError: 404 Client Error: Not Found for url: http://192.168.1.181:3334/api/octo/pic/', u'  File "octoprint_thespaghettidetective_beta/__init__.py", line 188, in main_loop', u'  File "octoprint_thespaghettidetective_beta/__init__.py", line 215, in post_jpg', u'  File "requests/models.py", line 940, in raise_for_status']
2020-07-21 07:50:49,831 - octoprint_thespaghettidetective_beta.utils - ERROR - Backing off 1.243342 seconds: 404 Client Error: Not Found for url: http://192.168.1.181:3334/api/octo/pic/
2020-07-21 07:50:51,572 - sentry.errors.uncaught - ERROR - [u'HTTPError: 404 Client Error: Not Found for url: http://192.168.1.181:3334/api/octo/pic/', u'  File "octoprint_thespaghettidetective_beta/__init__.py", line 188, in main_loop', u'  File "octoprint_thespaghettidetective_beta/__init__.py", line 215, in post_jpg', u'  File "requests/models.py", line 940, in raise_for_status']

2020-07-21 07:50:54,048 - tornado.application - ERROR - Uncaught exception GET /downloads/logs/octoprint.log (::ffff:192.168.1.54)

Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/web.py", line 2422, in get
    yield self.flush()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/web.py", line 953, in flush
    return self.request.connection.write(chunk, callback=callback)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/http1connection.py", line 437, in write
    self._pending_write = self.stream.write(self._format_chunk(chunk))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/http1connection.py", line 412, in _format_chunk
    "Tried to write more data than Content-Length")

HTTPOutputError: Tried to write more data than Content-Length
2020-07-21 07:50:54,049 - tornado.general - ERROR - Cannot send error response after headers written`
```

**Comment by nzzane** [comment]
Appears for some reason I had the beta version of TSD installed as well, uninstalled both and reinstalled main branch. 
All works now
