### ISSUE TITLE
docker web container: ValueError: Couldn't load manifest 'staticfiles.json' (version 1.0)

### ISSUE THREAD

**Issue by chris948** [TheSpaghettiDetective/TheSpaghettiDetective#264]
Sorry I can't be more help, I can't get into the container because it won't load, and I tried to revert to previous versions, I suspect the prior to python upgrade a few days ago would work, but when I build it, it just pulls the latest from here.

lsb_release -a
`No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal`

sudo docker version
`
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit: 
` 

sudo docker-compose version
`docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018`

using docker-compose up --build -d, this is the log

> Traceback (most recent call last):

  File "manage.py", line 15, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute

    output = self.handle(*args, **options)

  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 162, in handle

    if self.is_local_storage() and self.storage.location:

  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 216, in is_local_storage

    return isinstance(self.storage, FileSystemStorage)

  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 256, in inner

    self._setup()

  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 498, in _setup

    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()

  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 377, in __init__

    self.hashed_files = self.load_manifest()

  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 399, in load_manifest

    (self.manifest_name, self.manifest_version))

ValueError: Couldn't load manifest 'staticfiles.json' (version 1.0)

**Comment by kennethjiang** [comment]
What OS are you running for your host?

Also can you reclone the repo to a new folder and start over?

Also if you still have errors in the newly cloned repo, you can run `docker-compose up --build | tee compose.log`, then attach the `compose.log` file here.

**Comment by chris948** [comment]
I don't get it, I repulled twice without the extra logging, and it didn't work. I repulled with the logging and it took 10 minutes, but whatever it built actually works. I know that doesn't make sense, but thank you.

Thanks
