### ISSUE TITLE
Issues with newest master

### ISSUE THREAD

**Issue by derekslenk** [TheSpaghettiDetective/TheSpaghettiDetective#301]
Sometime since https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/commit/25c7fada2a0c20c276e707c1bcee251a4e889ccd I see a build error occuring when its going through requirements.txt and install grpcio.

25c7fada2a0c20c276e707c1bcee251a4e889ccd works but as soon as I switch to https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/commit/bf5f5429ccdad2a265e63e48c9539b324e3d8e45 I get the failure:
```
Collecting grpcio<2.0dev,>=1.29.0; extra == "grpc"
  Downloading grpcio-1.32.0.tar.gz (20.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j8q2rxhg/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j8q2rxhg/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4dyf03d3
         cwd: /tmp/pip-install-j8q2rxhg/grpcio/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-j8q2rxhg/grpcio/setup.py", line 212, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-j8q2rxhg/grpcio/setup.py", line 172, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cc': 'cc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```

I haven't been able to look into the commits/code differences to see what has changed too closely.

NB: I am building from a directory that has been building for a while now. I have my docker-compose.yml changes stashed when doing this. Maybe I have some weird file left over? Maybe you have a working version in your cache?

How to recreate:
```
git pull origin master
sudo docker-compose up --build -d
```

Versions:
```
➜  TheSpaghettiDetective git:(master) docker --version
Docker version 19.03.13, build 4484c46d9d
➜  TheSpaghettiDetective git:(master) docker-compose --version
docker-compose version 1.25.0, build 0a186604
➜  TheSpaghettiDetective git:(master) git log -8 --pretty=format:"%h - %an, %ar : %s" | tee
fd2a9ce - Kenneth Jiang, 25 hours ago : Refactor to remove redis module name confusion
bf5f542 - Kenneth Jiang, 5 days ago : Make base image slightly smaller
445774a - Kenneth Jiang, 5 days ago : Upgrade packages' version
3315910 - Kenneth Jiang, 6 days ago : Bug: missing the token auth based on path
54333d5 - Kenneth Jiang, 6 days ago : Make the default number of gunicorn to 1 for ml_api to use less memory and lower the hardware requirements
b6a9e1a - Kenneth Jiang, 6 days ago : Check in built bundles
f851d64 - Kenneth Jiang, 6 days ago : Support token in WS path for mobile app
25c7fad - Kenneth Jiang, 7 days ago : Check in built bundles%
```

**Comment by derekslenk** [comment]
If I had to guess by title alone its the checking in built bundles - maybe one had a dynamically linked executable?

**Comment by derekslenk** [comment]
I cannot reproduce on a fresh Debian or Ubuntu install. I guess this is a me issue. I'll just wipe the repo and start fresh I guess
