### ISSUE TITLE
[BUG] docker-compose fails to bring up website

### ISSUE THREAD

**Issue by paxxoid** [TheSpaghettiDetective/TheSpaghettiDetective#406]
I previously installed via docker without issue and today when I went to view the website was met with strange behavior. a view of the logs displayed that the database was locked:

```
django.request ERROR    Internal Server Error: /api/v1/octo/pic/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked
```

I brought down the containers, rebuilt and tried again but the database was never released no matter what I did. As a last resort, I removed all containers/images/volumes for the TSD, cloned a fresh copy, and attempted to bring up. I am now being met with the error and an unresponsive web interface.

```

itsme@home:/mnt/raid/TheSpaghettiDetective$ docker logs -f 9cdbc73f4dc9

0 static files copied to '/app/static_build', 278 unmodified, 564 post-processed.
/usr/local/lib/python3.7/site-packages/daphne/server.py:15: UserWarning: Something has already installed a non-asyncio Twisted reactor. Attempting to uninstall it; you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on.
  UserWarning,
```

During the build process

```

Deleting 'css/app.css.gz'
Deleting 'css/app.css'

278 static files copied to '/app/static_build', 798 post-processed.
/usr/local/lib/python3.7/site-packages/daphne/server.py:15: UserWarning: Something has already installed a non-asyncio Twisted reactor. Attempting to uninstall it; you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on.
  UserWarning,
Removing intermediate container a4ec5b2078c2
 ---> a9d3dac5da42

Successfully built a9d3dac5da42
Successfully tagged thespaghettidetective_web:latest

```
any ideas?

Update - the website finally came online but when logging in to admin for setup as this is now a fresh install, more database locked errors
```

django.channels.server INFO     HTTP GET /admin/login/?next=/admin/ 200 [0.01, 192.168.1.207:37700]
django.request ERROR    Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked


....


  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
daphne.ws_protocol ERROR    [Failure instance: Traceback: <class 'django.db.utils.OperationalError'>: database is locked
/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py:2839:processHandshake
/usr/local/lib/python3.7/site-packages/txaio/tx.py:366:as_future
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:151:maybeDeferred
/usr/local/lib/python3.7/site-packages/daphne/ws_protocol.py:83:onConnect
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:151:maybeDeferred
/usr/local/lib/python3.7/site-packages/daphne/server.py:200:create_application
/usr/local/lib/python3.7/site-packages/channels/routing.py:54:__call__
/app/api/authentication.py:38:__call__
/usr/local/lib/python3.7/site-packages/safedelete/queryset.py:88:get
/usr/local/lib/python3.7/site-packages/django/db/models/query.py:402:get
/usr/local/lib/python3.7/site-packages/django/db/models/query.py:256:__len__
/usr/local/lib/python3.7/site-packages/safedelete/queryset.py:138:decorator
/usr/local/lib/python3.7/site-packages/django/db/models/query.py:1242:_fetch_all
/usr/local/lib/python3.7/site-packages/django/db/models/query.py:55:__iter__
/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py:1133:execute_sql
/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py:67:execute
/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py:76:_execute_with_wrappers
/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py:84:_execute
/usr/local/lib/python3.7/site-packages/django/db/utils.py:89:__exit__
/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py:84:_execute
/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py:383:execute
]
django.channels.server INFO     WebSocket DISCONNECT /ws/dev/ [192.168.1.220:35484]
django.channels.server ERROR    HTTP POST /admin/login/?next=/admin/ 500 [9.22, 192.168.1.207:37700]

```

**Comment by kennethjiang** [comment]
@paxxoid This looks like an environment issue. You will get help much faster by asking this question in our discord server: https://discord.gg/NcZkQfj

Let me know if you really think this is a code issue. Otherwise I'll close it assuming it's an environment/configuration question.

**Comment by paxxoid** [comment]
Going to close this issue  for now- I was able to launch the docker image yesterday night and while I was receiving database lock errors initially, I have not seen any today when I monitored. 
Thanks
