### ISSUE TITLE
web server keeps restarting

### ISSUE THREAD

**Issue by keawepoo** [TheSpaghettiDetective/TheSpaghettiDetective#89]
I just installed everything. On trying to access the web page it kicks back saying that there isnt anything located there... After a big of digging I think it might have something to do with this? (see image)
[https://i.imgur.com/p5Sa0Pm.png](https://i.imgur.com/p5Sa0Pm.png)

Thank you.

**Comment by kennethjiang** [comment]
It looks like both `web` and `tasks` containers keep on restarting. can you do `docker-compose log -f web` and `docker-compose log -f tasks` to check if there are any errors?

**Comment by keawepoo** [comment]
No such command: log
[https://i.imgur.com/8dZxHdO.png](https://i.imgur.com/8dZxHdO.png)

**Comment by kennethjiang** [comment]
Sorry, it is `docker-compose logs -f tasks`

**Comment by keawepoo** [comment]
A ton of errors... Do I need to install python?
[https://i.imgur.com/JmwmRAv.jpg](https://i.imgur.com/JmwmRAv.jpg)

**Comment by kennethjiang** [comment]
Can you try `docker-compose down && docker-compose up -d` and see what happens?

**Comment by kennethjiang** [comment]
@keawepoo Do you still need another help on this issue?

**Comment by keawepoo** [comment]
@kennethjiang Sorry I didnt see the emails....
[https://i.imgur.com/yIKiQZr.jpg](https://i.imgur.com/yIKiQZr.jpg)

**Comment by jsiemek** [comment]
I've same problem.
Ubuntu 18.04.3
docker-ce  version 19.03.1, build 74b1e89


thespaghettidetective_web_1 log:

```
django.db.utils.OperationalError: no such table: django_site,
,
0 static files copied to '/app/static_build', 202 unmodified, 446 post-processed.,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute,
    return self.cursor.execute(sql, params),
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute,
    return Database.Cursor.execute(self, query, params),
sqlite3.OperationalError: no such table: django_site,
,
The above exception was the direct cause of the following exception:,
,
Traceback (most recent call last):,
  File "manage.py", line 15, in <module>,
    execute_from_command_line(sys.argv),
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line,
    utility.execute(),
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute,
    self.fetch_command(subcommand).run_from_argv(self.argv),
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv,
    self.execute(*args, **cmd_options),
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute,
    self.check(),
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check,
    include_deployment_checks=include_deployment_checks,,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks,
    issues.extend(super()._run_checks(**kwargs)),
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks,
    return checks.run_checks(**kwargs),
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks,
    new_errors = check(app_configs=app_configs),
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config,
    return check_resolver(resolver),
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver,
    return check_method(),
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check,
    for pattern in self.url_patterns:,
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__,
    res = instance.__dict__[self.name] = self.func(instance),
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns,
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module),
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__,
    res = instance.__dict__[self.name] = self.func(instance),
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module,
    return import_module(self.urlconf_name),
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module,
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed,
  File "/app/config/urls.py", line 21, in <module>,
    path('', include('app.urls')),,
  File "/usr/local/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include,
    urlconf_module = import_module(urlconf_module),
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module,
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed,
  File "/app/app/urls.py", line 3, in <module>,
    from . import views,
  File "/app/app/views.py", line 15, in <module>,
    from .forms import *,
  File "/app/app/forms.py", line 10, in <module>,
    from .telegram_bot import bot as telebot,
  File "/app/app/telegram_bot.py", line 16, in <module>,
    MORE_INFO_LINK = site.build_full_url('/printers/'),
  File "/app/lib/site.py", line 8, in build_full_url,
    domain_name = Site.objects.first().domain,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method,
    return getattr(self.get_queryset(), name)(*args, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 605, in first,
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__,
    self._fetch_all(),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all,
    self._result_cache = list(self._iterable_class(self)),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__,
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql,
    cursor.execute(sql, params),
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute,
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute),
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers,
    return executor(sql, params, many, context),
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute,
    return self.cursor.execute(sql, params),
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__,
    raise dj_exc_value.with_traceback(traceback) from exc_value,
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute,
    return self.cursor.execute(sql, params),
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute,
    return Database.Cursor.execute(self, query, params),
django.db.utils.OperationalError: no such table: django_site,
```
also thespaghettidetective_tasks_1 log show similar errors:

```
    _main(),
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main,
    cmd.execute_from_commandline(argv),
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline,
    super(CeleryCommand, self).execute_from_commandline(argv))),
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline,
    return self.handle_argv(self.prog_name, argv[1:]),
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv,
    return self.execute(command, argv),
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute,
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0]),
  File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 223, in run_from_argv,
    return self(*args, **options),
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__,
    ret = self.run(*args, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 257, in run,
    **kwargs),
  File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 96, in __init__,
    self.app.loader.init_worker(),
  File "/usr/local/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker,
    self.import_default_modules(),
  File "/usr/local/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules,
    raise response,
  File "/usr/local/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send,
    response = receiver(signal=self, sender=sender, **named),
  File "/usr/local/lib/python3.6/site-packages/celery/fixups/django.py", line 82, in on_import_modules,
    self.worker_fixup.validate_models(),
  File "/usr/local/lib/python3.6/site-packages/celery/fixups/django.py", line 121, in validate_models,
    run_checks(),
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks,
    new_errors = check(app_configs=app_configs),
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config,
    return check_resolver(resolver),
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver,
    return check_method(),
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check,
    for pattern in self.url_patterns:,
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__,
    res = instance.__dict__[self.name] = self.func(instance),
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns,
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module),
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__,
    res = instance.__dict__[self.name] = self.func(instance),
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module,
    return import_module(self.urlconf_name),
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module,
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed,
  File "/app/config/urls.py", line 21, in <module>,
    path('', include('app.urls')),,
  File "/usr/local/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include,
    urlconf_module = import_module(urlconf_module),
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module,
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed,
  File "/app/app/urls.py", line 3, in <module>,
    from . import views,
  File "/app/app/views.py", line 15, in <module>,
    from .forms import *,
  File "/app/app/forms.py", line 10, in <module>,
    from .telegram_bot import bot as telebot,
  File "/app/app/telegram_bot.py", line 16, in <module>,
    MORE_INFO_LINK = site.build_full_url('/printers/'),
  File "/app/lib/site.py", line 8, in build_full_url,
    domain_name = Site.objects.first().domain,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method,
    return getattr(self.get_queryset(), name)(*args, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 605, in first,
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__,
    self._fetch_all(),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all,
    self._result_cache = list(self._iterable_class(self)),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__,
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql,
    cursor.execute(sql, params),
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute,
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute),
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers,
    return executor(sql, params, many, context),
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute,
    return self.cursor.execute(sql, params),
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__,
    raise dj_exc_value.with_traceback(traceback) from exc_value,
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute,
    return self.cursor.execute(sql, params),
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute,
    return Database.Cursor.execute(self, query, params),
django.db.utils.OperationalError: no such table: django_site,
```

**Comment by edsai** [comment]
I've got the same issue.

**Comment by kennethjiang** [comment]
Thank you folks for reporting this bug and providing the info. It is a bug we introduced recently. Please pull the latest and it should work now.
